### PR TITLE
Update README with Vim 8 pack installation

### PR DESCRIPTION
**Pull request by NeuralSandwich**
Add instructions show how to perform an installation using Vim 8's native package manager

### CODE REVIEW

**Comment by frasercrmck** [comment]
Thanks! I can't personally comment on whether this works, but I trust you :)

We could perhaps move the "native" instructions to the first place in the list?

**Comment by NeuralSandwich** [comment]
Yeah, it is working, I updated the README as I was moving away from Vundle and trying to simplify my setup.

I didn't want to be presumptuous and left it at the bottom. I can move that up top, not sure which distros are on v8 yet.

**Comment by NeuralSandwich** [comment]
Updated to put native at the top :+1:

**Comment by frasercrmck** [comment]
I hadn't forgotten about this! (I totally had :smile:)

**Pull request merged**
